gencode_gene:
  adapter:
    module: biocypher_metta.adapters.gencode_gene_adapter
    cls: GencodeGeneAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/gencode/Drosophila_melanogaster.BDGP6.46.59.gtf.gz
      gene_alias_file_path: ./aux_files/Drosophila_melanogaster.gene_info.gz

  outdir: gencode/gene
  nodes: True
  edges: False


gencode_transcripts:
  adapter:
    module: biocypher_metta.adapters.gencode_transcript_adapter
    cls: GencodeAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/gencode/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      type: transcript
      label: transcript

  outdir: gencode/transcript
  nodes: True
  edges: False


gencode_exon:
  adapter:
    module: biocypher_metta.adapters.gencode_exon_adapter
    cls: GencodeExonAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/gencode/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz

  outdir: gencode/exon
  nodes: True
  edges: False

transcribed_to:
  adapter:
    module: biocypher_metta.adapters.gencode_transcript_adapter
    cls: GencodeAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/gencode/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      type: transcribed to
      label: transcribed_to

  outdir: gencode
  nodes: False
  edges: True

transcribed_from:
  adapter:
    module: biocypher_metta.adapters.gencode_transcript_adapter
    cls: GencodeAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/gencode/Drosophila_melanogaster.BDGP6.46.59.chr.gtf.gz
      type: transcribed from
      label: transcribed_from

  outdir: gencode
  nodes: False
  edges: True


uniprotkb_sprot:
  adapter:
    module: biocypher_metta.adapters.uniprot_protein_adapter
    cls: UniprotProteinAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/uniprot/uniprot_sprot_invertebrates_DMEL.dat.gz

  outdir: uniprot
  nodes: True
  edges: False

uniprotkb_sprot_translates_to:
  adapter:
    module: biocypher_metta.adapters.uniprot_adapter
    cls: UniprotAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/uniprot/uniprot_sprot_invertebrates_DMEL.dat.gz
      type: translates to
      label: translates_to

  outdir: uniprot
  nodes: False
  edges: True

uniprotkb_sprot_translates_of:
  adapter:
    module: biocypher_metta.adapters.uniprot_adapter
    cls: UniprotAdapter
    args:
      filepath: /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/input/full/uniprot/uniprot_sprot_invertebrates_DMEL.dat.gz
      type: translation of
      label: translation_of

  outdir: uniprot
  nodes: False
  edges: True

pathway:
  adapter:
    module: biocypher_metta.adapters.reactome_pathway_adapter
    cls: ReactomePathwayAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/reactome/ReactomePathways.txt
      pubmed_map_path: /mnt/hdd_2/abdu/biocypher_data/reactome/ReactionPMIDS.txt

  outdir: reactome
  nodes: True
  edges: False

genes_pathways:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/reactome/Ensembl2Reactome_All_Levels.txt
      label: genes_pathways

  outdir: reactome
  nodes: False
  edges: True

parent_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/reactome/ReactomePathwaysRelation.txt
      label: parent_pathway_of

  outdir: reactome
  nodes: False
  edges: True

child_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/reactome/ReactomePathwaysRelation.txt
      label: child_pathway_of

  outdir: reactome
  nodes: False
  edges: True

tflink:
    adapter:
        module: biocypher_metta.adapters.tflink_adapter
        cls: TFLinkAdapter
        args:
          filepath: /mnt/hdd_2/abdu/biocypher_data/tflink/tflink_homo_sapiens_interactions.tsv.gz
          entrez_to_ensemble_map: ./aux_files/entrez_to_ensembl.pkl

    outdir: tflink
    nodes: False
    edges: True

string:
  adapter:
    module: biocypher_metta.adapters.string_ppi_adapter
    cls: StringPPIAdapter
    args:
      filepath: /mnt/hdd_2/abdu/biocypher_data/string/string_human_ppi_v12.0.txt.gz
      ensembl_to_uniprot_map: ./aux_files/string_ensembl_uniprot_map.pkl

  outdir: string
  nodes: False
  edges: True

