Title: BioCypher graph schema configuration file
# ---
# "Named Things"
# ---

gene:
  represented_as: node
  preferred_id: ensemble
  input_label: gene
  properties:
    chr: str
    start: int
    end: int
    name: str
    gene_type: str
    synonyms: str[]
    source: str
    version: str

protein:
  represented_as: node
  preferred_id: uniprot
  input_label: protein
  properties:
    accessions: int
    organism_id: int
    name: str
    synonyms: str[]

transcript:
  represented_as: node
  input_label: transcript
  properties:
    chr: str
    start: int
    end: int
    gene_name: str
    transcript_name: str
    transcript_id: str
    transcript_type: str
    source: str
    version: str
    source_url: str
  is_a: nucleic acid entity
  description: >-
    An RNA synthesized on a DNA or RNA template by an RNA polymerase.
  exact_mappings:
    - SO:0000673
    - SIO:010450
    - WIKIDATA:Q7243183
    - dcid:RNATranscript
  in_subset:
    - model_organism_database
  
regulatory region:
  represented_as: node
  input_label: regulatory_region
  accessible_via:
    name: regulatory_regions
    description: 'Retrieve regulatory regions data. Example: region = chr1:1157520-1158189 or biochemical_activity = CA or source = ENCODE_SCREEN (ccREs)'
    filter_by: _id, chr, type
    filter_by_range: start, end
    return: _id, chr, start, end, type, biochemical_activity, biochemical_activity_description, type, source, source_url
  properties:
    chr: str
    start: int
    end: int
    biochemical_activity: str
    biochemical_activity_description: str
  aliases: ['regulatory element', 'accessible dna element']
  description: >-
    A region (or regions) of the genome that contains known or putative regulatory elements
    that act in cis- or trans- to affect the transcription of gene
  is_a: biological entity
  mixins:
    - genomic entity
    - chemical entity or gene or gene product
    - physical essence
    - ontology class
  exact_mappings:
    - SO:0005836
    - SIO:001225
    - WIKIDATA:Q3238407

ontology term:
  is_a: ontology class
  represented_as: node
  input_label: ontology term
  properties:
    uri: str
    term_name: str
    description: str
    synonyms: obj
    source: str
    subontology: str
    subset: str

pathway:
  is_a: biological process
  exact_mappings:
    - PW:0000001
    - WIKIDATA:Q4915012
  narrow_mappings:
    - SIO:010526
    - GO:0007165
  represented_as: node
  input_label: pathway
  properties:
    id_version: str
    name: str
    is_in_disease: boolean
    name_aliases: array
    species: str
    disease_ontology_terms: array
    go_biological_process: str
    is_top_level_pathway: boolean
# ---
# Associations
# ---

transcribed to:
  represented_as: edge
  is_a: related to at instance level
  domain: gene
  range: transcript
  input_label: transcribed_to
  source: gene
  target: transcript
  properties:
    source: str
    version: str
    source_url: str
  description: >-
    inverse of transcribed from
  exact_mappings:
    - RO:0002511
    - SIO:010080

transcribed from:
  is_a: related to at instance level
  represented_as: edge
  domain: transcript
  range: gene
  input_label: transcribed_from
  source: transcript
  target: gene
  properties:
    source: str
    version: str
    source_url: str
  description: >-
    x is transcribed from y if and only if x is synthesized from template y
  exact_mappings:
    - RO:0002510
    - SIO:010081

translates to:
  is_a: related to at instance level
  represented_as: edge
  input_label: translates_to
  source: transcript
  target: protein
  properties:
    source: str
    source_url: str
  inverse: translation of
  description: >-
    x (amino acid chain/polypeptide) is the ribosomal translation of y (transcript) if and only if a ribosome
    reads y (transcript) through a series of triplet codon-amino acid adaptor activities (GO:0030533)
    and produces x (amino acid chain/polypeptide)
  close_mappings:
    - RO:0002513
    - SIO:010082

translation of:
  is_a: related to at instance level
  represented_as: edge
  input_label: translation_of
  source: protein
  target: transcript
  description: >-
    inverse of translates to
  inverse: translates to
  close_mappings:
    - RO:0002512
    - SIO:010083

gene to pathway association:
  description: >-
    An interaction between a gene or gene product and a biological process or pathway.
  is_a: association
  mixins:
    - gene to entity association mixin
  represented_as: edge
  input_label: genes_pathways
  source: gene
  target: pathway

parent pathway of:
    is_a: related to at concept level
    description: >-
      holds between two pathways where the domain class is a parent pathway of the range class
    represented_as: edge
    input_label: parent_pathway_of
    source: pathway
    target: pathway

child pathway of:
    is_a: related to at concept level
    description: >-
      holds between two pathways where the domain class is a child pathway of the range class
    represented_as: edge
    input_label: child_pathway_of
    source: pathway
    target: pathway

ontology relationship:
  is_a: related to at instance level
  represented_as: edge
  input_label: ontology_relationship
  source: ontology term
  target: ontology term
  properties:
    rel_type: str
    source: str

go gene product:
  is_a: related to at instance level
  represented_as: edge
  input_label: go_gene_product
  source: ontology term
  target: protein
  properties:
    qualifier: obj
    db_reference: obj
    evidence: str

gene to gene coexpression association:
  description: >-
    Indicates that two genes are co-expressed,
    generally under the same conditions.
  is_a: gene to gene association
  defining_slots:
    - subject
    - predicate
    - object
  mixins:
    - gene expression mixin
  slot_usage:
    predicate:
      subproperty_of: coexpressed with
      symmetric: true
  represented_as: edge
  input_label: coexpressed_with
  source: gene
  target: gene
  properties:
    score: int

regulatory element to gene expression association:
  description: >-
    An association between a regulatory element and the expression of a gene
  is_a: association
  defining_slots:
    - subject
    - predicate
    - object
  slot_usage:
    object:
      range: gene
    predicate:
      subproperty_of: genetic association
  represented_as: edge
  input_label: regulates_gene
  label_as_edge: ELEMENT_GENE
  source: regulatory region
  target: gene
  properties:
    score: int
    source: str
    source_url:  str
    biological_context: str


transcription factor to gene association:
  description: >-
    An regulatory association between a transcription factor and its target gene
  is_a: gene to gene association
  represented_as: edge
  input_label: regulates
  source: gene
  target: gene
  properties:
    evidence: str[]
    detection_method: str
    source: str[]
    evidence_type: str

post translational interaction:
  is_a: pairwise molecular interaction
  represented_as: edge
  input_label: interacts_with
  source: protein
  target: protein
  properties:
    score: float