# 2025/09: started changes to handle multiple species data.

from collections import defaultdict
from biocypher_metta.adapters import Adapter

# From Github issue description (https://github.com/rejuve-bio/biocypher-kg/issues/180):

# Reactome data relating reactions to pathways describe a protein and its different roles in a reaction that is 'part_of' a pathway. S
# ome examples are shown below.
# From Reactome data, is possible to create (at least) the following causal relations between a protein and (a reaction or a pathway):

# 1. protein negatively regulates reaction
    # RO:0002212: http://purl.obolibrary.org/obo/RO_0002212
# 2. protein positively regulates reaction
    # RO:0002213: http://purl.obolibrary.org/obo/RO_0002213
# 3. protein negatively regulates pathway
    # RO:0002212: http://purl.obolibrary.org/obo/RO_0002212
# 4. protein positively regulates pathway
    # RO:0002213: http://purl.obolibrary.org/obo/RO_0002213
# 5. protein regulates reaction/pathway
    # RO:0002211: http://purl.obolibrary.org/obo/RO_0002211

# Besides, if a protein is an input of a reaction (or pathway) it enables that reaction (or pathway). Similarly, if a protein is an
# output of a reaction (or pathway) it is produced_by that reaction (or pathway).

# 5. protein is an input of a reaction (or pathway): it enables that reaction (or pathway).
# 6. protein is an output of a reaction (or pathway): it is produced_by that reaction (or pathway).

# 6. protein enables reaction/pathway
    # RO:0002211: http://purl.obolibrary.org/obo/RO_0002327
# 7. protein produced_by reaction/pathway
    # RO:0002211: http://purl.obolibrary.org/obo/RO_0003001



# According to Reactome AI bot (https://reactome.org/chat/) there are only 5 roles in the data:
# Input: 
    # This refers to the substrates or reactants that are required for a biochemical reaction to occur. 
    # Inputs are the starting materials that undergo transformation during the reaction. For example, 
    # in the reaction where ATP is converted to cAMP, ATP is the input.
# Output: 
    # This term describes the products that result from a biochemical reaction. 
    # Outputs are the end products formed after the transformation of the inputs. 
    # Continuing with the previous example, cAMP is the output of the reaction where ATP is converted.
# Catalyst: 
    # A catalyst is a substance that increases the rate of a chemical reaction without being consumed in the process. 
    # Catalysts work by lowering the activation energy required for the reaction to proceed. 
    # In many biochemical pathways, enzymes act as catalysts. For instance, in the conversion of ATP to cAMP, the enzyme ADCY3 acts as a catalyst.
# Negative: 
    # In biochemical contexts, "negative" often refers to a regulatory mechanism that decreases the activity of a pathway or reaction. 
    # Negative regulators can inhibit the function of enzymes or other proteins, thereby reducing the rate of a reaction or the production of a product. 
    # For example, certain proteins may act as negative regulators of signaling pathways, ensuring that the response does not become excessive.
# Positive: 
    # Conversely, "positive" refers to regulatory mechanisms that enhance or increase the activity of a pathway or reaction. 
    # Positive regulators can activate enzymes or promote the production of products, thereby facilitating the reaction. 
    # For example, certain phosphorylation events can act as positive regulators, enhancing the activity of kinases involved in signaling pathways.


# Data file for reaction_to_pathway and protein_role_in_reaction:  reactome_reaction_exporter_All_species.txt  (version 95)
# 
# <<----::: Specially generated by Reactome folks under request.  Thanks Reactome folks! :::---->>
#
# We will generate next versions by ourselves: there're directives from Reactome folks to do so in a follow-up email to saulo@singularitynet.io
# subject: ReactomeReactions.txt ???
# 
# (to be equal to the other files, the header was removed)
#
# pathway_id	reaction_id	reaction_name	uniprot_acc	role_in_reaction
# R-CEL-1059683	R-CEL-1112538	Phosphorylated STAT1, STAT3 form dimers	D3YT30	[input, output]
# R-CEL-1059683	R-CEL-1112538	Phosphorylated STAT1, STAT3 form dimers	Q20977	[input, output]
# R-DME-1059683	R-DME-1112538	Phosphorylated STAT1, STAT3 form dimers	Q24151	[input, output]
# R-DME-1059683	R-DME-1112587	STAT1 and STAT3 dimers translocate to the nucleus	Q24151	[input, output]
# R-DME-109704	R-DME-109699	PI3K-containing complexes phosphorylate PIP2 to PIP3	E1JHB7	[catalyst]
# R-DME-110314	R-DME-5652005	RAD18:UBE2B or RBX1:CUL4:DDB1:DTL ubiquitin ligase complex binds PCNA:POLD,POLE:RPA:RFC associated with damaged dsDNA	P17917	[input, output]
# R-HSA-1059683	R-HSA-1067651	IL6:IL6R-2 binds IL6ST:JAK1, JAK2, (TYK2)	O60674	[input, output]
# R-HSA-1059683	R-HSA-1067651	IL6:IL6R-2 binds IL6ST:JAK1, JAK2, (TYK2)	P05231	[input, output, negative]
# R-HSA-1059683	R-HSA-1067667	IL6 binds IL6R	P08887	[input, output, negative]

class ReactomeInferenceEdgesAdapter(Adapter):

    ALLOWED_LABELS = ['enables', 'produced_by', 'regulates', 'negatively_regulates', 'positively_regulates']

    def __init__(self, filepath, label, write_properties, add_provenance, taxon_id, ensembl_uniprot_map_path=None):
        """
        Added taxon_id parameter to handle multiple species data.

        If taxon_id is None, all pathways defined in organism_taxon_map
        will be translated into Atom space. Otherwise, only data for
        the specified species will be processed.
        """        
        if label not in ReactomeInferenceEdgesAdapter.ALLOWED_LABELS:
            raise ValueError('Invalid label. Allowed values: ' +
                             ', '.join(ReactomeInferenceEdgesAdapter.ALLOWED_LABELS))
        self.filepath = filepath
        self.dataset = label
        self.label = label
        self.source = "REACTOME"
        self.source_url = "https://reactome.org"
        self.fbpp_to_uniprot = {}               # dict to map FBpp to UniProt ids and to avoid remote connections during runtime
        self.taxon_id = taxon_id
        super(ReactomeInferenceEdgesAdapter, self).__init__(write_properties, add_provenance)

    def get_edges(self):
        organism_taxon_map = {
            'R-CEL': 6239,  # Caenorhabditis elegans (cel)
            'R-DME': 7227,  # Drosophila melanogaster (dmel)
            # 'R-NUL': 7227,  # some reactions of Drosophila melanogaster (dmel)  <----:: CAUTION: some other reactome entities use R-NULL
            'R-HSA': 9606,  # Homo sapiens (hsa)
            # Add more organisms here as needed
            'R-MMU': 10090,   # Mus musculus (mmu)
            'R-RNO': 10116,   # Rattus norvegicus
        }        
        roles_to_label_map = defaultdict(lambda: None)
        roles_to_label_map['input'] = ('enables', 'RO_0002327')
        roles_to_label_map['output'] = ('produced_by', 'RO_0003001')
        roles_to_label_map['catalyst'] = ('regulates', 'RO_0002211')
        roles_to_label_map['negative'] = ('negatively_regulates', 'RO_0002212')
        roles_to_label_map['positive'] = ('positively_regulates', 'RO_0002213')
        with open(self.filepath) as input_file:
            base_props = {}
            if self.write_properties and self.add_provenance:
                base_props['source'] = self.source
                base_props['source_url'] = self.source_url
            not_mapped_no_processing = 0
            total_in_species_records = 0
            edges_dict = defaultdict(lambda: None)  # to avoid protin-to-pathway duplicates
            for line in input_file:
                data = line.strip().split('\t')

                if self.label in self.ALLOWED_LABELS:
                    pathway_id = data[0].strip()
                    reaction_id = data[1].strip()
                    uniprot_id = data[3].strip()   
                    protein_roles = data[4].strip()                 
                    organism_pathway_prefix = pathway_id[:5]
                    organism_reaction_prefix = reaction_id[:5]
                    if (organism_pathway_prefix != organism_reaction_prefix):
                        print(f"Pathway and reaction have different organism prefixes: {organism_pathway_prefix} != {organism_reaction_prefix}\n"
                              f"Need to check it. Letting it out of the loop.\nRecord: {data}")
                        not_mapped_no_processing += 1
                        total_in_species_records += 1
                        continue
                    if organism_reaction_prefix not in organism_taxon_map:
                        total_in_species_records += 1
                        continue
                    if organism_taxon_map[organism_reaction_prefix] != self.taxon_id:
                        total_in_species_records += 1
                        continue
                    total_in_species_records += 1
                    protein_roles = protein_roles.replace('[', '').replace(']', '').replace(' ', '').split(',')
                    for protein_role in protein_roles:
                        label = roles_to_label_map[protein_role][0]
                        edges_key = f'{uniprot_id}_{protein_role}_{pathway_id}'  
                        if not edges_key in edges_dict:
                            props = base_props.copy()
                            props['relation_ontology_term'] = roles_to_label_map[protein_role][1]
                            props['taxon_id'] = self.taxon_id
                            edges_dict[edges_key] = True                                                
                            yield uniprot_id, ('pathway', pathway_id), label, props
                        yield uniprot_id, ('reaction', reaction_id), label, props
            print(f'Entities not linked: {not_mapped_no_processing} out of {total_in_species_records}')

